fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

e_text_book_api:
    resource: "@eTextBookAPIBundle/Controller/"
    type:     annotation
    prefix:   /

e_text_book_lounge:
    resource: "@eTextBookLoungeBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
      _locale: ru|kg

e_text_book_lounge_homepage_def_loc:
    path: /
    defaults:  { _controller: eTextBookLoungeBundle:Default:index }

e_text_book_spawn:
    resource: "@eTextBookSpawnBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path:   /logout


