security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    staff:  { password: swordfish, roles: [ 'ROLE_STAFF' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            http_basic:
              realm: "Staff Area"
            logout: ~

    access_control:
        - { path: ^/book/edit/, roles: ROLE_STAFF }
        - { path: ^/login, roles: ROLE_STAFF }
